# SwiftLint Configuration

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - first_where
  - sorted_first_last

included:
  - AppMedical

excluded:
  - Pods
  - build
  - DerivedData

line_length:
  warning: 120
  error: 200

function_body_length:
  warning: 100
  error: 200

reporter: "xcode"
